// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CardViewFitDemo.tsx": () => import("../components/mockups/CardViewFitDemo.tsx"),
  "./components/mockups/CardViewRegionsGuide.tsx": () => import("../components/mockups/CardViewRegionsGuide.tsx"),
  "./components/mockups/PhoneFrame.tsx": () => import("../components/mockups/PhoneFrame.tsx")
};
